# Generated by Django 6.0.3 on 2026-05-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
